print("номер рейса: ")
n = input()
print("название авиакомпании (на русском €зыке): ")
namer = input()
print("название авиакомпании (на английском €зыке): ")
namee = input()
print ("название авиакомпании (на английском €зыке): ")
sir = input()
print("название авиакомпании (на английском €зыке): ")
sie = input()
print(f"«аканчиваетс€ посадка на рейс {n} {namer} до {sir}\nThis is the final boarding call for {namee} flight {n} to {sie}")