print("номер рейса: ")
n = input()
print("название авиакомпании (на русском языке): ")
namer = input()
print("название авиакомпании (на английском языке): ")
namee = input()
print ("город прилета (на русском языке): ")
sir = input()
print("город прилета (на английском языке): ")
sie = input()
print(f"Заканчивается посадка на рейс {n} {namer} до {sir}\nThis is the final boarding call for {namee} flight {n} to {sie}")